title: HER Lab
description: A research team led by Dr Yue Li, focusing on advancing the fields of cultural heritage, education, and entertainment by novel technologies and reality-based experiences.
theme: just-the-docs

url: https://chiran.top/

aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: her

markdown: kramdown
kramdown:
  input: GFM
  
languages: ["en", "zh"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true
